services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8088:8088"
    volumes:
      - ./backend/temp_uploads:/app/temp_uploads
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/mydatabase
    command: uvicorn main:app --host 0.0.0.0 --port 8088 --timeout-keep-alive 600
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
