services:
  postgres:
    image: postgres:13
    container_name: postgres-db-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      # 將容器的 5432 port 映射到您電腦的 5432 port
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network-dev

  redis:
    image: redis:latest
    container_name: redis-broker-dev
    ports:
      # 將容器的 6379 port 映射到您電腦的 6379 port
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network-dev

volumes:
  postgres_data_dev:

networks:
  app-network-dev:
    driver: bridge
